version: '3.8'

networks:
  databases-frontend:
    external: true
    name: databases-frontend

services:
  frontend:
    deploy:
      labels: #Labels voor reverse proxy
        - "traefik.enable=true"
        - "traefik.http.routers.databases-frontend.rule=Host(`dashboard.${PRIMARY_DOMAIN}`)"
        - "traefik.http.routers.databases-frontend.middlewares=authtraefik"
        - "traefik.http.routers.databases-frontend.entrypoints=websecure"
        - "traefik.http.routers.databases-frontend.tls=true"
        - "traefik.http.routers.databases-frontend.tls.certresolver=le"
        - "traefik.http.services.databases-frontend.loadbalancer.server.port=${PORT}"
      mode: replicated
      replicas: 2
      placement:
        max_replicas_per_node: 1
        #        preferences:
        #          - spread: node.id
        constraints: # alleen op manager/worker node
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 5
        window: 10s
      update_config:
        parallelism: 1
        delay: 5s
      resources:
        limits:
          memory: 512M
          cpus: '0.4'
        reservations:
          memory: 64M
    networks:
      - databases-frontend
