version: '3.8'
networks:
  databases-frontend:
    external: true
    name: databases-frontend-dev

services:
#  backend:
#    image: mcdefault/databases-backend:1.0.0-alpine3.15
#    deploy:
#      mode: replicated
#      replicas: 1
#    env_file:
#      - .env
  frontend:
    image: mcdefault/databases-frontend:1.0.0-nginx1.23.1-alpine #todo  te veranderen naar hsleiden registery
    deploy:
      mode: replicated
      replicas: 1
    env_file:
      - .env
