volumes:
  postgres:

networks:
  databases-db-dev:
    name: databases-db-dev
  hemiron-ntw-compose:
    external: true
    name: hemiron-ntw-compose

services: # docker compose up --build
  db: # docker compose up --build db
    container_name: db
    restart: unless-stopped
    env_file:
      - .env.dev
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./init-a-user-db.sh:/docker-entrypoint-initdb.d/init-a-user-db.sh
      - ./init-z-schema-tables.sh:/docker-entrypoint-initdb.d/init-z-schema-tables.sh
    ports:
      - "5432:5432"
    networks:
      - databases-db-dev
  adminer:
    environment:
      - ADMINER_DEFAULT_SERVER=db
    networks:
      - databases-db-dev
      - hemiron-ntw-compose
    labels:
      - "traefik.docker.network=hemiron-ntw-compose"
      # For Url adminer.${PRIMARY_DOMAIN}
      - "traefik.http.routers.adminer.rule=Host(`adminer.${PRIMARY_DOMAIN?Variable not set!}`)"
      - "traefik.http.routers.adminer.entrypoints=web"
      - "traefik.http.routers.adminer.tls=false"
      - "traefik.http.services.adminer.loadbalancer.server.port=8080"
