version: '3.8'
networks:
  databases-frontend:
    external: true
    name: databases-db

services:
  db:
    image: postgres:15.0
    env_file:
      - .env
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
