networks:
  databases-db-dev:
    name: databases-db-dev

services: # docker compose up --build
  db: # docker compose up --build db
    container_name: db
    restart: unless-stopped
    env_file:
      - .env.dev
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
#      - ./entrypoint.sql:/docker-entrypoint-initdb.d/entrypoint.sql
    ports:
      - "5432:5432"
    networks:
      - databases-db-dev
  adminer:
    networks:
      - databases-db-dev
