set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER "$PG_USER_USERNAME" WITH PASSWORD '$PG_USER_PASSWORD';
	CREATE DATABASE "$PG_USER_DATABASE";
	GRANT ALL PRIVILEGES ON DATABASE "$PG_USER_DATABASE" TO "$PG_USER_USERNAME";
EOSQL