stages:
  - pre-check
  - build
  - test
image: docker:latest

CI_PRE_CHECK:
  stage: pre-check
  tags:
    - swarm
  script:
    - echo "pre checking"
    - ls -l
    - docker images

CI_BUILD:
  stage: build
  tags:
    - swarm
  script:
    - echo "building"

CI_TEST:
  stage: test
  tags:
    - swarm
  script:
    - echo "Testing"