image: nielsprins/ipsenh-ci

cache:
  untracked: true
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - backend/node_modules/
    - frontend/node_modules/

stages:
  - setup
  - test
  - build
  - deploy

backend_setup:
  stage: setup
  script:
    - (cd ./backend && npm install --include=dev)

frontend_setup:
  stage: setup
  script:
    - (cd ./frontend && npm install --include=dev)

backend_audit:
  stage: test
  allow_failure: true
  needs:
    - backend_setup
  script:
    - (cd ./backend && npm audit)

frontend_audit:
  stage: test
  allow_failure: true
  needs:
    - frontend_setup
  script:
    - (cd ./frontend && npm audit)

backend_lint:
  stage: test
  needs:
    - backend_setup
  script:
    - (cd ./backend && npm run lint)

frontend_lint:
  stage: test
  needs:
    - frontend_setup
  script:
    - (cd ./frontend && npm run lint)

backend_test:
  stage: test
  needs:
    - backend_setup
  script:
    - (cd ./backend && npm run test)

frontend_test:
  stage: test
  needs:
    - frontend_setup
  script:
    - (cd ./frontend && npm run test)

backend_build:
  stage: deploy
  image: docker:latest
  needs:
    - backend_lint
    - backend_test
  script:
    - (cd ./backend && docker build -t backend:latest .)
  only:
    - main

frontend_build:
  stage: deploy
  image: docker:latest
  needs:
    - frontend_lint
    - frontend_test
  script:
    - (cd ./backend && docker build -t frontend:latest .)
  only:
    - main
