stages:
  - pre-check
  - build
  - test
image: docker:latest

CI_Pre_Check:
  stage: pre-check
  tags:
    - swarm
  script:
    - echo "pre checking"
    - ls -l
    - docker images

CI_Build:
  stage: build
  tags:
    - swarm
  script:
    - echo "building"
    - ls -l
    - docker images

CI_TEST:
  stage: test
  tags:
    - swarm
  script:
    - echo "Testing"
    - ls -l
    - docker ps