stages:
  - pre-check
  - build
  - test
  - verify
image: docker:latest

CI_PRE_CHECK:
  stage: pre-check
  tags:
    - swarm
  script:
    - echo "pre checking"
    - ls -l
    - docker version
    - docker container ls
    - docker images

CI_BUILD:
  stage: build
  tags:
    - swarm
  script:
    - echo "building"
    - docker build -t pipeline-build-test .

CI_TEST:
  stage: test
  tags:
    - swarm
  script:
    - echo "Testing"

CI_VERIFY:
  stage: verify
  tags:
    - swarm
  script:
    - echo "Verify"
    - docker container ls
    - docker service ls