#trigger_job:
#  trigger:
#    include: child-pipeline.yml

include:
  - local: "child-pipeline.yml"
  - local: "backend/child-pipeline-backend.yml"
  - local: "frontend/child-pipeline-frontend.yml"

default:
  timeout: 2 hours # terminate any job taking longer than 1 hour

stages:
  - pre-check
  - analyse
  - test
  - build
  - deploy
  - verify

image: docker:latest

.job_docker_template: &template
  retry: 2
  tags:
    - docker
  only:
    refs:
      - main
      - merge_requests

CI_PRE_CHECK:
  stage: pre-check
  <<: *template
  allow_failure: true #On failure All jobs after this one, will not halt.
  script:
    - echo "pre checking"
    - ls -l
    - docker version
#    - userdump #test failure. All jobs after this one, not ran (with allow_failure false).


