stages:
  - pre-check
  - build
  - test
  - verify
image: docker:latest

CI_PRE_CHECK:
  stage: pre-check
  tags:
    - swarm
  only:
    - feature/pipeline-api
  script:
    - echo "pre checking"
    - ls -l
    - docker version
    - docker container ls
    - docker images

CI_BUILD:
  stage: build
  variables:
    PROJECT_ID: test
    IMAGE_NAME_FINAL: $IMAGE_NAME/$PROJECT_ID:1.0.$CI_PIPELINE_IID-ubuntu
  tags:
    - swarm
  only:
    - feature/pipeline-api
  before_script:
    - echo "building"
  script:
    - docker login -u pipeline -p $BUILD_TOKEN $CI_REGISTRY
    - docker build -t $IMAGE_NAME_FINAL .
    - docker image push $IMAGE_NAME_FINAL

CI_TEST:
  stage: test
  tags:
    - swarm
  only:
    - feature/pipeline-api
  script:
    - echo "Testing"
    - docker container ls
    - docker image ls

#CI_VERIFY: #no manager
#  stage: verify
#  tags:
#    - swarm
#  only:
#    - feature/pipeline-api
#  script:
#    - echo "Verify"
#    - docker container ls
#    - docker service ls