#only branch template
x-only-branch:
  &only-branch
  only:
    - feature/pipeline-api
stages:
  - pre-check
  - build
  - test
  - verify
image: docker:latest

CI_PRE_CHECK:
  stage: pre-check
  tags:
    - swarm
  <<: *only-branch
  script:
    - echo "pre checking"
    - ls -l
    - docker version
    - docker container ls
    - docker images

CI_BUILD:
  stage: build
  tags:
    - swarm
  <<: *only-branch
  script:
    - echo "building"
    - docker login -u pipeline -p $BUILD_TOKEN registry.inf-hsleiden.nl
    - docker build -t registry.inf-hsleiden.nl/pipeline-build-test-1 .

CI_TEST:
  stage: test
  tags:
    - swarm
  <<: *only-branch
  script:
    - echo "Testing"
    - docker container ls
    - docker image ls

CI_VERIFY:
  stage: verify
  tags:
    - swarm
  <<: *only-branch
  script:
    - echo "Verify"
    - docker container ls
    - docker service ls