stages:
  - pre-check
  - build
  - test
  - verify
image: docker:latest

CI_PRE_CHECK:
  stage: pre-check
  tags:
    - swarm
  only:
    - $BRANCH_TO_TRIGGER_RUNNERS
  allow_failure: true #On failure All jobs after this one, will not halt.
  script:
    - echo "pre checking"
    - ls -l
    - docker version
    - docker container ls
    - docker images
    - userdump #test failure. All jobs after this one, not ran

CI_BUILD:
  stage: build
  variables:
    BASE_IMAGE: ubuntu
    PROJECT_ID: test
    IMAGE_NAME_FINAL: $IMAGE_NAME/$PROJECT_ID:1.0.$CI_PIPELINE_IID-$BASE_IMAGE
  tags:
    - swarm
  only:
    - $BRANCH_TO_TRIGGER_RUNNERS
  before_script:
    - echo "building"
    - docker login -u pipeline -p $BUILD_TOKEN $CI_REGISTRY
  script:
    - docker build -t $IMAGE_NAME_FINAL .
  after_script:
    - docker image push $IMAGE_NAME_FINAL
    - docker images

CI_BUILD_V2:
  stage: build
  variables:
    BASE_IMAGE: ubuntu
    PROJECT_ID: testv2
    IMAGE_NAME_FINAL: $IMAGE_NAME_BASE/$PROJECT_ID:1.0.$CI_PIPELINE_IID-$BASE_IMAGE
  tags:
    - swarm
  only:
    - $BRANCH_TO_TRIGGER_RUNNERS
  before_script:
    - echo "building"
    - docker login -u pipeline -p $BUILD_TOKEN $CI_REGISTRY
  script:
    - docker build -t $IMAGE_NAME_FINAL .
  after_script:
    - docker image push $IMAGE_NAME_FINAL
    - docker images

CI_TEST:
  stage: test
  tags:
    - swarm
  only:
    - $BRANCH_TO_TRIGGER_RUNNERS
  script:
    - echo "Testing"
    - docker container ls
    - docker image ls

#CI_VERIFY: #no manager
#  stage: verify
#  tags:
#    - swarm
#  only:
#    - $BRANCH_TO_TRIGGER_RUNNERS
#  script:
#    - echo "Verify"
#    - docker container ls
#    - docker service ls