#trigger_job:
#  trigger:
#    include: child-pipeline.yml

include:
  - local: "child-pipeline.yml"
  - local: "backend/child-pipeline-backend.yml"

default:
  timeout: 2 hours # terminate any job taking longer than 1 hour

stages:
  - pre-check
  - build
  - test
  - deploy
#  - verify

image: docker:latest

.job_docker_template: &template
  tags:
    - swarm
  only:
    refs:
      - feature/pipeline-api

CI_PRE_CHECK:
  stage: pre-check
  <<: *template
  allow_failure: true #On failure All jobs after this one, will not halt.
  script:
    - echo "pre checking"
    - ls -l
    - docker version
    - docker container ls
    - docker images ls
    - sleep 20
#    - userdump #test failure. All jobs after this one, not ran (with allow_failure false).

#CI_BUILD:
#  stage: build
#  variables:
#    BASE_IMAGE: ubuntu
#    PROJECT_ID: test
#    IMAGE_NAME_FINAL: $IMAGE_NAME_BASE/$PROJECT_ID:1.0.$CI_PIPELINE_IID-$BASE_IMAGE
##  rules:
##    - if: $CI_COMMIT_BRANCH == "feature/pipeline-api"
##      changes:
##        - Dockerfile
#  retry: 2
#  inherit:
#    default: false
#  <<: *template
#  needs: [] # no dependencies
#  before_script:
#    - echo "building"
#    - docker login -u pipeline -p $BUILD_TOKEN $CI_REGISTRY
#    - sleep 10
#  script:
#    - docker build -t $IMAGE_NAME_FINAL .
#  after_script:
#    - docker image push $IMAGE_NAME_FINAL
#    - docker images ls
##  cache:
##    key: $IMAGE_NAME_FINAL
##    paths:
##      - ./
#  artifacts: # create artifact when job fails
#    name: $IMAGE_NAME_FINAL
#    when: on_failure
#    paths:
#      - ./
#    expire_in: 2 days
#    exclude:
#      - .gitlab-ci.yml

#CI_BUILD_V2:
#  stage: build
#  variables:
#    BASE_IMAGE: ubuntu
#    PROJECT_ID: testv2
#    IMAGE_NAME_FINAL: $IMAGE_NAME_BASE/$PROJECT_ID:1.0.$CI_PIPELINE_IID-$BASE_IMAGE
#  <<: *template
#  needs: [CI_PRE_CHECK] # dependent on CI_PRE_CHECK. only runs after it
#  before_script:
#    - echo "building"
#    - docker login -u pipeline -p $BUILD_TOKEN $CI_REGISTRY
#    - sleep 10
#  script:
#    - docker build -t $IMAGE_NAME_FINAL .
#  after_script:
#    - docker image push $IMAGE_NAME_FINAL
#    - docker images ls

CI_TEST:
  stage: test
  <<: *template
  when: manual # only execute when approved manually
  script:
    - echo "Testing"
    - docker container ls
    - docker image ls

#CI_Deploy_Testing:
#  stage: deploy
#  <<: *template
#  script:
#    - sudo docker run -itd -p 80:80 httpd
#  environment:
#    name: Testing



#CI_VERIFY: #no manager
#  stage: verify
#  <<: *template
#  script:
#    - echo "Verify"
#    - docker container ls
#    - docker service ls