stages:
  - build
CI_Build:
  stage: build
  tags:
    - docker
  script:
    - echo "building"
    - ls -l
    - apt-get -y update
    - apt-get -y install docker
    - apt-get -y install docker.io
    - dockerd
    - docker images
