stages:
    - test

CI_Cleanup:
    stage: test
    tags:
        - swarm
    parallel: 5 # we have 5 runners
    only:
        - feature/pipeline-api
    script:
        - docker image prune -a -f # cleanup unused images after each time to reduce disk space waste
