version: '3.8'
services:
  backend:
    deploy:
      mode: replicated
      replicas: 2
      labels:
        traefik.enable: "true"
        traefik.http.routers.databases-backend.entrypoints: websecure
        traefik.http.routers.databases-backend.middlewares: authtraefik
        traefik.http.routers.databases-backend.rule: Host(`api.inf-hsleiden.nl`)
        traefik.http.routers.databases-backend.tls: "true"
        traefik.http.routers.databases-backend.tls.certresolver: le
        traefik.http.services.databases-backend.loadbalancer.server.port: "3000"
      update_config:
        parallelism: 1
        delay: 5s
      resources:
        limits:
          cpus: "0.4"
          memory: "536870912"
        reservations:
          memory: "67108864"
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 5
        window: 10s
      placement:
        constraints:
        - node.role == worker
        max_replicas_per_node: 2
    environment:
      PORT: "3000"
      PRIMARY_DOMAIN: inf-hsleiden.nl
      TEST_FILE: /run/secrets/TEST_FILE
      TEST2_FILE: /run/secrets/OPTIONAL_FILE
    image: mcdefault/databases-backend:1.0.0-alpine3.15
    networks:
      databases-backend: null
networks:
  databases-backend:
    name: databases-backend
    external: true
