stages:
    - analysis
    - build
    - test
    - deploy
    - verify

.job_docker_template: &template
    retry: 2
    tags:
        - swarm
    only:
        refs:
            - sonarqube_based_on_tutorial1
            - main
        changes:
            - backend/**/*

CI_ANALYSE_BACKEND:
    image:
        name: sonarsource/sonar-scanner-cli:latest
        entrypoint: [""]
    stage: analysis
    variables:
        SONAR_TOKEN: sqp_3b49c6daf0fe369599acb79f8fb640018110c7b9
        SONAR_HOST_URL: http://localhost:9000
        SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
        GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
    cache:
        key: "${CI_JOB_NAME}"
        paths:
            - .sonar/cache
    allow_failure: true
    only:
        - develop
        - sonarqube_based_on_tutorial1
    needs: [ CI_PRE_CHECK ] # no dependencies.
    before_script:
        - echo "before analysis"
    script:
        - echo "analysis"
    after_script:
        - echo "after analysis"
    artifacts: # create artifact when job fails
        name: $IMAGE_NAME_FINAL
        when: on_failure
        paths:
            - ./
        expire_in: 2 days
        exclude:
            - .gitlab-ci.yml



CI_BUILD_BACKEND:
    stage: build
    variables:
        BASE_IMAGE: node18-alpine
        PROJECT_ID: backend
        IMAGE_NAME_FINAL: $IMAGE_NAME_BASE/$PROJECT_ID:1.0.$CI_PIPELINE_IID-$BASE_IMAGE
    inherit:
        default: false
    <<: *template
#    when: manual # only execute when approved manually
    needs: [CI_PRE_CHECK] # no dependencies.
    before_script:
        - echo "building for production"
        - docker login -u pipeline -p $BUILD_TOKEN $CI_REGISTRY
    script:
        - docker build -t $IMAGE_NAME_FINAL --target production $PROJECT_ID/.
    after_script:
        - docker image push $IMAGE_NAME_FINAL # push with versioning
        - docker image tag $IMAGE_NAME_FINAL $IMAGE_NAME_BASE/$PROJECT_ID:production # re-tag same image and push with production tag
        - docker image push $IMAGE_NAME_BASE/$PROJECT_ID:production
        - docker images ls
    artifacts: # create artifact when job fails
        name: $IMAGE_NAME_FINAL
        when: on_failure
        paths:
            - ./
        expire_in: 2 days
        exclude:
            - .gitlab-ci.yml

CI_DEPLOY_BACKEND: #$BUILD_TOKEN  $CI_REGISTRY  $SSH_DEPLOYMENT_IP   $SSH_DEPLOYMENT_HOST $SSH_DEPLOYMENT_USER $SSH_PRIVATE_KEY
    stage: deploy
    variables:
        STACK_FILE_NAME: backend-stack.yml
        DEPLOY_FILE_NAME: deploy-backend.sh
        PROJECT_ID: backend
    <<: *template
    when: manual # only execute when approved manually.
    needs: [CI_BUILD_BACKEND]
    before_script:
        - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
        - eval $(ssh-agent -s)
        - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
        - mkdir -p ~/.ssh
        - chmod 700 ~/.ssh
        - echo $SSH_DEPLOYMENT_IP $SSH_DEPLOYMENT_HOST >> /etc/hosts
        - echo $SSH_DEPLOYMENT_USER@$SSH_DEPLOYMENT_HOST
        - docker login -u pipeline -p $BUILD_TOKEN $CI_REGISTRY
        # - ssh -o StrictHostKeyChecking=no -t $SSH_DEPLOYMENT_USER@$SSH_DEPLOYMENT_HOST 'bash -s' < prepare.sh #create project dir
        - ssh -o StrictHostKeyChecking=no $SSH_DEPLOYMENT_USER@$SSH_DEPLOYMENT_HOST bash -c 'ls -l'
        - ssh -o StrictHostKeyChecking=no $SSH_DEPLOYMENT_USER@$SSH_DEPLOYMENT_HOST bash -c 'docker network ls'
    script:
        - scp -o StrictHostKeyChecking=no ./$PROJECT_ID/$STACK_FILE_NAME $SSH_DEPLOYMENT_USER@$SSH_DEPLOYMENT_HOST:/home/student/databases/$STACK_FILE_NAME #copy over stack files
        - ssh -o StrictHostKeyChecking=no -t $SSH_DEPLOYMENT_USER@$SSH_DEPLOYMENT_HOST 'bash -s' < ./$PROJECT_ID/$DEPLOY_FILE_NAME #execute file

CI_VERIFY_BACKEND:
    stage: verify
    variables:
        VERIFY_FILE_NAME: verify-backend.sh
        PROJECT_ID: backend
    <<: *template
    needs: [CI_DEPLOY_BACKEND]
    before_script:
        - echo "Verify"
        - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
        - eval $(ssh-agent -s)
        - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
        - mkdir -p ~/.ssh
        - chmod 700 ~/.ssh
        - echo $SSH_DEPLOYMENT_IP $SSH_DEPLOYMENT_HOST >> /etc/hosts
        - docker login -u pipeline -p $BUILD_TOKEN $CI_REGISTRY
    script:
        - ssh -o StrictHostKeyChecking=no -t $SSH_DEPLOYMENT_USER@$SSH_DEPLOYMENT_HOST 'bash -s' < ./$PROJECT_ID/$VERIFY_FILE_NAME #execute verify file
