version: '3.8'
networks:
  databases-frontend:
    external: true
    name: databases-frontend-dev
  databases-db:
    external: true
    name: databases-db

services:
  scanner:
    image: sonarsource/sonar-scanner-cli:4.8
    env_file:
      - .env
  backend:
    image: registry.inf-hsleiden.nl/2223.ipsenh-p1-p2/databases/backend:1.0.0-node18-alpine
    deploy:
      mode: replicated
      replicas: 1
    extra_hosts:
      - "manager-1.inf-hsleiden:192.168.195.109"
      - "manager-2.inf-hsleiden:192.168.195.168"
    env_file:
      - .env