networks:
  databases-frontend-dev:
    name: databases-frontend-dev
  databases-db-dev:
    name: databases-db-dev


services: # docker compose up --build
  backend: # docker compose up --build backend
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: api
    image: registry.inf-hsleiden.nl/2223.ipsenh-p1-p2/databases/backend:dev-1.0.0-node18-alpine #schrijft prod image over
    command: npm run start:dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${PORT}:${PORT}
    networks:
      - databases-frontend-dev
      - databases-db-dev