image: docker:stable

services:
  - docker:dind

#before_script:
  #- docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"

deploy_to_swarm:
  stage: deploy
  script:
    - docker network ls
    - docker stack deploy --with-registry-auth -c docker-stack.yml redis
