services:
  redis:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6379:6379"
    networks:
      - redis

  redis-ui:
    image: marian/rebrow
    ports:
      - '5001:5001'
    networks:
      - redis

networks:
  redis:
    external: true
    name: redis